![Pandas Comic from Realpython](./img/pandas_comic.png)

(c) [Realpython.com](https://realpython.com)

In [23]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Einführung

In unserer kurzen Betrachtung von *NumPy* im ersten Kapitel sahen wir, dass auch mit NumPy Matrizen aus unterschiedlichen Objekten (Zahlen, Strings, Datumsobjekten, usw.) bilden kann. So könnten wir Daten in tabellarischer Form abbilden.

```
date1 = datetime(2022, 6, 22)
date2 = datetime(1980, 10, 29)

test = np.array([[date1, date2],
                [1, 2],
                ['a', 'b']])
```

Jedoch sind wir es gewohnt, dass Daten in tabellarischer Form oft anders "daherkommen". Dies hat vor allem mit dem Begriff *tidy data* zu tun. Tabellarische Daten sind dann *tidy*, wenn sie
  - für jede Messung/jedes Individuum *genau eine* Zeile,
  - für jede Zeile genau einen einzigartigen Schlüssel,
  - für jede Variable *genau eine* Spalte und
  - für jede Spalte genau einen Datentyp (String, Number, Datetime, usw.)
  
haben.
  
Das obige Beispiel müsste also tabellarisch so aussehen:

Index  | Date       | Number | String
-------|------------|--------|-------
0      | 2022-06-22 | 1      | a
1      | 1980-10-29 | 2      | b

Genau zu diesem Zweck der einfachen *Erzeugung* und *Manipulation* von tabellarischen Daten gibt es seit 2010 für Python das Modul [**Pandas**](https://pandas.pydata.org).

Tabellarische Daten werden in *Pandas* in einem sog. *DataFrame* gespeichert. Dieser enthält die einzelnen Variablen/Spalten als Pandas *Series Objekte* und einen *Index*.

# deskriptive Datenanalyse mit Pandas

Die Daten, die wir für unsere Analysen als Grundlage haben, liegen uns meist als Textdateien oder in Form von Datenbankeinträgen vor.

Wir wollen uns in diesem Kurs der Einfachheit halber mit Daten in Textform beschäftigen. Auch hier gibt es viele Formate, wie Daten in Reintext strukturiert werden. Komplexere Formate sind XML und JSON, einfachere Formate sind z.B. CSV Dateien. Letztere wollen wir auch für diesen Kurs verwenden. Bei CSV Dateien stehen die Werte pro Eintrag in einer Spalte. Die einzelnen Variablen werden meist mit Kommata von einander abgetrennt (daher auch der Name *Comma Seperated Values*). Längere Werte (wie, z.B. Text) werden noch einmal mit Hochkommata abgegrenzt.

So sieht eine Beispiel-CSV aus:

```
id,first_name,last_name,class,language,rating,favorite_subjects
02,Stefan,Boehringer,5,german,3.2,'history, english'
13,Kathrin,Boehringer,5,german,3.8,'religion, german'
```

Allerdings ist die Separierung per Kommata, die im angloamerikanischen Raum präferiert wird, im deutschen Sprachraum, wegen der Verwendung anderer Dezimaltrenner und Hochkommata problematisch. Hier hat sich eher dieses Format eingebürgert:

```
id;Vorname;Nachname;Klasse;Sprache;Note;Lieblingsfaecher
02;Stefan;Böhringer;5;Deutsch;3,2;"Geschichte, Englisch"
13;Kathrin;Böhringer;5;Deutsch;3,8;"Religion, Deutsch"
```

Beide Varianten können natürlich mit Pandas eingelesen werden.

So können wir nun die Funktion [`.read_csv()`](https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html) des Pandas Moduls aufrufen, die es uns ermöglicht, CSV Dateien einzulesen.

## CSV Dateien einlesen

In [4]:
df = pd.read_csv("./data/pokedex.csv")

Die Funktion `.read_csv()`, wie übrigens alle anderen `pd.read_...()` Funktionen aus dem Pandas Modul speichern die Werte in der Pandas eigenen Datenstruktur **DataFrame**.

### Funktionen für die erste Analyse und Orientierung

Es gibt mehrere Funktionen, mit denen man sich einen Überblick über einen DataFrame verschaffen kann.

- `.head()` gibt die ersten Zeilen (Defaultwert ist 5) eines DataFrames zurück.

In [5]:
df.head()

,Unnamed: 0,pokedex_number,name,german_name,japanese_name,generation,status,species,type_number,type_1,...,against_ground,against_flying,against_psychic,against_bug,against_rock,against_ghost,against_dragon,against_dark,against_steel,against_fairy
0,0,1,Bulbasaur,Bisasam,フシギダネ (Fushigidane),1,Normal,Seed Pokémon,2,Grass,...,1.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5
1,1,2,Ivysaur,Bisaknosp,フシギソウ (Fushigisou),1,Normal,Seed Pokémon,2,Grass,...,1.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5
2,2,3,Venusaur,Bisaflor,フシギバナ (Fushigibana),1,Normal,Seed Pokémon,2,Grass,...,1.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5
3,3,3,Mega Venusaur,Bisaflor,フシギバナ (Fushigibana),1,Normal,Seed Pokémon,2,Grass,...,1.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5
4,4,4,Charmander,Glumanda,ヒトカゲ (Hitokage),1,Normal,Lizard Pokémon,1,Fire,...,2.0,1.0,1.0,0.5,2.0,1.0,1.0,1.0,0.5,0.5

Es fällt auf, dass ein Index automatisch von Pandas vergeben wurde, der in der CSV-Datei als erste Spalte enthalten war. Wir können Pandas mitteilen, dass es nun diese Spalte als Index benutzen soll.

In [6]:
df.index = df['Unnamed: 0']

df.index.name = 'Index'

Anschliessend können wir die überflüssige Spalte "Unnamed: 0" löschen.

In [7]:
df = df.drop(columns=['Unnamed: 0'])

- `.tail()` gibt gegenüber `.head()` die letzten Zeilen (Defaultwert ebenfalls 5) eines Dataframes zurück.

In [8]:
df.tail(7)

,pokedex_number,name,german_name,japanese_name,generation,status,species,type_number,type_1,type_2,...,against_ground,against_flying,against_psychic,against_bug,against_rock,against_ghost,against_dragon,against_dark,against_steel,against_fairy
Index,,,,,,,,,,,,,,,,,,,,,
1038,894,Regieleki,Regieleki,レジエレキ (Regieleki),8,Sub Legendary,Elektron Pokémon,1,Electric,NaN,...,2.0,0.5,1.0,1.0,1.0,1.0,1.0,1.0,0.5,1.0
1039,895,Regidrago,Regidrago,レジドラゴ (Regidrago),8,Sub Legendary,Dragon Orb Pokémon,1,Dragon,NaN,...,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0
1040,896,Glastrier,Polaross,ブリザポス (Burizaposu),8,Sub Legendary,Wild Horse Pokémon,1,Ice,NaN,...,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,2.0,1.0
1041,897,Spectrier,Phantoross,レイスポス (Reisuposu),8,Sub Legendary,Swift Horse Pokémon,1,Ghost,NaN,...,1.0,1.0,1.0,0.5,1.0,2.0,1.0,2.0,1.0,1.0
1042,898,Calyrex,Coronospa,バドレックス (Budrex),8,Legendary,King Pokémon,2,Psychic,Grass,...,0.5,2.0,0.5,4.0,1.0,2.0,1.0,2.0,1.0,1.0
1043,898,Calyrex Ice Rider,Coronospa,バドレックス (Budrex),8,Legendary,High King Pokémon,2,Psychic,Ice,...,1.0,1.0,0.5,2.0,2.0,2.0,1.0,2.0,2.0,1.0
1044,898,Calyrex Shadow Rider,Coronospa,バドレックス (Budrex),8,Legendary,High King Pokémon,2,Psychic,Ghost,...,1.0,1.0,0.5,1.0,1.0,4.0,1.0,4.0,1.0,1.0

In unserem DataFrame gibt es also 1045 Zeilen. Dies sehen wir aber nur, weil Pandas beim Einlesen der CSV Datei einen fortlaufenden Index vergeben hat. Der Index könnte aber, wie die Spalten auch mit einem anderen Wert gelabelt werden. Z.B. könnten die Namen der Pokemon den Index bilden. Wie man das macht, sehen wir später noch. Wollen wir dennoch zuverlässig wissen, welche Zeilen- und Spaltenlänge ein Dataframe hat, können wir das Attribut `.shape` abrufen. Der erste Wert gibt dabei die Anzahl an Zeilen, der zweite Wert die Anzahl an Spalten an.

In [9]:
df.shape

(1045, 50)

- `.info()` listet übersichtlich alle Informationen zur Beschreibung eines Dataframes auf. Dazu gehören die Anzahl der Einträge, die verschiedenen Spalten inkl. Namen, wie viele Zeilen einen Wert in der Spalte haben und welchen Datentyp die jeweilige Spalte hat.

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1045 entries, 0 to 1044
Data columns (total 50 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   pokedex_number    1045 non-null   int64
 1   name              1045 non-null   object
 2   german_name       1045 non-null   object
 3   japanese_name     1045 non-null   object
 4   generation        1045 non-null   int64
 5   status            1045 non-null   object
 6   species           1045 non-null   object
 7   type_number       1045 non-null   int64
 8   type_1            1045 non-null   object
 9   type_2            553 non-null    object
 10  height_m          1045 non-null   float64
 11  weight_kg         1044 non-null   float64
 12  abilities_number  1045 non-null   int64
 13  ability_1         1042 non-null   object
 14  ability_2         516 non-null    object
 15  ability_hidden    813 non-null    object
 16  total_points      1045 non-null   int64
 17  hp                1045 non-null   int64
 18  attack            1045 non-null   int64
 19  defense           1045 non-null   int64
 20  sp_attack         1045 non-null   int64
 21  sp_defense        1045 non-null   int64
 22  speed             1045 non-null   int64
 23  catch_rate        1027 non-null   float64
 24  base_friendship   930 non-null    float64
 25  base_experience   925 non-null    float64
 26  growth_rate       1044 non-null   object
 27  egg_type_number   1045 non-null   int64
 28  egg_type_1        1042 non-null   object
 29  egg_type_2        285 non-null    object
 30  percentage_male   872 non-null    float64
 31  egg_cycles        1044 non-null   float64
 32  against_normal    1045 non-null   float64
 33  against_fire      1045 non-null   float64
 34  against_water     1045 non-null   float64
 35  against_electric  1045 non-null   float64
 36  against_grass     1045 non-null   float64
 37  against_ice       1045 non-null   float64
 38  against_fight     1045 non-null   float64
 39  against_poison    1045 non-null   float64
 40  against_ground    1045 non-null   float64
 41  against_flying    1045 non-null   float64
 42  against_psychic   1045 non-null   float64
 43  against_bug       1045 non-null   float64
 44  against_rock      1045 non-null   float64
 45  against_ghost     1045 non-null   float64
 46  against_dragon    1045 non-null   float64
 47  against_dark      1045 non-null   float64
 48  against_steel     1045 non-null   float64
 49  against_fairy     1045 non-null   float64
dtypes: float64(25), int64(12), object(13)
memory usage: 416.4+ KB

### Exkurs 7: Datentypen in Pandas

Pandas benutzt intern die Datentypen des Moduls *NumPy* und bringt noch einige eigene mit. Wie NumPy mit Pandas zusammenhängt, werden wir später noch sehen. Die wichtigsten Datentypen, die Pandas benutzt sind folgende:

| Datentyp | Art der Daten | Bezeichnung in Pandas |
|:---|:---:|:---|
| Int64DType | Ganz- und Fließkommazahlen | int64, int32, float64 ... |
| StringDType |  Sequenz von Zeichen | string |
| BooleanDType | Logisches `True` und `False` | boolean |
| CategoricalDType | kategorische Daten | category |
| DatetimeTZDtype | Zeitzonen sensitives Datums- und Zeitformat | datetime64 |

Mit der Funktion `.astype()` kann man Spalten eines Dataframes einen neuen Typ geben. So sind z.B. die vier Variablen *status*, *species*, *type_1* und *type_2* in unserem Pokemon Datensatz *kategoriale* Daten.

Mit der `.astype()` Funktion können wir diese Spalten in einen *CategoricalDType* umwandeln. Dazu müssen wir der Funktion Schüssel-Wert-Paare (key-value-pairs) übergeben, wobei in Python für diese Datenstruktur das sog. *Dictionary* zur Verfügung steht. Als Schüssel wird jeweils der Spaltenindex bzw. Spaltenname und als Wert die Art des DTypes angegeben.

Ruft man nur die Funktion `.astype()` auf, so wird nur ein sog. "View" generiert, aber der Dataframe nicht verändert. Möchte man die Veränderung aber "speichern" so muss man den View erneut dem Dataframe zuweisen; man überschreibt ihn gewissermaßen.

In [11]:
df = df.astype({'status': 'category', 'species': 'category', 'type_1': 'category', 'type_2': 'category'})

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1045 entries, 0 to 1044
Data columns (total 50 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   pokedex_number    1045 non-null   int64
 1   name              1045 non-null   object
 2   german_name       1045 non-null   object
 3   japanese_name     1045 non-null   object
 4   generation        1045 non-null   int64
 5   status            1045 non-null   category
 6   species           1045 non-null   category
 7   type_number       1045 non-null   int64
 8   type_1            1045 non-null   category
 9   type_2            553 non-null    category
 10  height_m          1045 non-null   float64
 11  weight_kg         1044 non-null   float64
 12  abilities_number  1045 non-null   int64
 13  ability_1         1042 non-null   object
 14  ability_2         516 non-null    object
 15  ability_hidden    813 non-null    object
 16  total_points      1045 non-null   int64
 17  hp                1045 non-null   int64
 18  attack            1045 non-null   int64
 19  defense           1045 non-null   int64
 20  sp_attack         1045 non-null   int64
 21  sp_defense        1045 non-null   int64
 22  speed             1045 non-null   int64
 23  catch_rate        1027 non-null   float64
 24  base_friendship   930 non-null    float64
 25  base_experience   925 non-null    float64
 26  growth_rate       1044 non-null   object
 27  egg_type_number   1045 non-null   int64
 28  egg_type_1        1042 non-null   object
 29  egg_type_2        285 non-null    object
 30  percentage_male   872 non-null    float64
 31  egg_cycles        1044 non-null   float64
 32  against_normal    1045 non-null   float64
 33  against_fire      1045 non-null   float64
 34  against_water     1045 non-null   float64
 35  against_electric  1045 non-null   float64
 36  against_grass     1045 non-null   float64
 37  against_ice       1045 non-null   float64
 38  against_fight     1045 non-null   float64
 39  against_poison    1045 non-null   float64
 40  against_ground    1045 non-null   float64
 41  against_flying    1045 non-null   float64
 42  against_psychic   1045 non-null   float64
 43  against_bug       1045 non-null   float64
 44  against_rock      1045 non-null   float64
 45  against_ghost     1045 non-null   float64
 46  against_dragon    1045 non-null   float64
 47  against_dark      1045 non-null   float64
 48  against_steel     1045 non-null   float64
 49  against_fairy     1045 non-null   float64
dtypes: category(4), float64(25), int64(12), object(9)
memory usage: 411.6+ KB

Sehen Sie, wie nun die Spalten 5, 6, 8 und 9 den Datentyp `category` haben.

Wir können uns sogar ansehen, welche DType Kategorien die Spalte "type_1" nun enthält.

In [13]:
df.type_1.dtypes.categories

Index(['Bug', 'Dark', 'Dragon', 'Electric', 'Fairy', 'Fighting', 'Fire',
       'Flying', 'Ghost', 'Grass', 'Ground', 'Ice', 'Normal', 'Poison',
       'Psychic', 'Rock', 'Steel', 'Water'],
      dtype='object')

Eine letzte Methode, um uns einen Überblick über den DataFrame zu verschaffen, ist die Methode `.describe()`. Sie gibt eine Reihe deskriptiver statistischer Kennwerte zurück, dazu gehören die zentrale Tendenz, die Streuung und die Form der Verteilung eines Datensatzes, wobei NaN-Werte (also fehlende Werte) ausgeschlossen sind.

In [14]:
df.describe()

,pokedex_number,generation,type_number,height_m,weight_kg,abilities_number,total_points,hp,attack,defense,...,against_ground,against_flying,against_psychic,against_bug,against_rock,against_ghost,against_dragon,against_dark,against_steel,against_fairy
count,1045.000000,1045.000000,1045.000000,1045.000000,1044.000000,1045.000000,1045.000000,1045.000000,1045.000000,1045.000000,...,1045.000000,1045.000000,1045.000000,1045.000000,1045.000000,1045.000000,1045.000000,1045.000000,1045.000000,1045.000000
mean,440.769378,4.098565,1.529187,1.374067,71.216571,2.268900,439.353110,70.067943,80.476555,74.670813,...,1.082297,1.168900,0.977273,0.998086,1.238278,1.018660,0.977033,1.071053,0.981579,1.091148
std,262.517231,2.272788,0.499386,3.353349,132.259911,0.803154,121.992897,26.671411,32.432728,31.259462,...,0.782683,0.592145,0.501934,0.610411,0.696560,0.568056,0.375812,0.465178,0.501753,0.536285
min,1.000000,1.000000,1.000000,0.100000,0.100000,0.000000,175.000000,1.000000,5.000000,5.000000,...,0.000000,0.250000,0.000000,0.000000,0.250000,0.000000,0.000000,0.250000,0.000000,0.000000
25%,212.000000,2.000000,1.000000,0.600000,9.000000,2.000000,330.000000,50.000000,55.000000,50.000000,...,0.500000,1.000000,1.000000,0.500000,1.000000,1.000000,1.000000,1.000000,0.500000,1.000000
50%,436.000000,4.000000,2.000000,1.000000,29.500000,2.000000,458.000000,68.000000,77.000000,70.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
75%,670.000000,6.000000,2.000000,1.600000,70.500000,3.000000,515.000000,82.000000,100.000000,90.000000,...,1.500000,1.000000,1.000000,1.000000,2.000000,1.000000,1.000000,1.000000,1.000000,1.000000
max,898.000000,8.000000,2.000000,100.000000,999.900000,3.000000,1125.000000,255.000000,190.000000,250.000000,...,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,2.000000,4.000000,4.000000,4.000000

Von den 50 Variablen könnten 37 mit der `.describe()` Methode angezeigt werden, aber nur 20 werden tatsächlich angezeigt. Wir sollten Pandas in diesem Jupyter Notebook so einstellen, dass wir immer alle Spalten sehen.

In [15]:
pd.set_option('display.max_columns', df.shape[1])

Ausserdem ist es bei dieser Ansicht etwas mühselig, immer so weit nach rechts zu scrollen, um den Überblick über die komplette Ausgabe von `.describe()` zu haben. Wir können aber jederzeit das Attribute `.T` (großes "T" für "transpose") aufrufen, das Zeilen mit Spalten vertauscht.

In [16]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
pokedex_number,1045.0,440.769378,262.517231,1.00,212.0,436.0,670.0,898.0
generation,1045.0,4.098565,2.272788,1.00,2.0,4.0,6.0,8.0
type_number,1045.0,1.529187,0.499386,1.00,1.0,2.0,2.0,2.0
height_m,1045.0,1.374067,3.353349,0.10,0.6,1.0,1.6,100.0
weight_kg,1044.0,71.216571,132.259911,0.10,9.0,29.5,70.5,999.9
abilities_number,1045.0,2.268900,0.803154,0.00,2.0,2.0,3.0,3.0
total_points,1045.0,439.353110,121.992897,175.00,330.0,458.0,515.0,1125.0
hp,1045.0,70.067943,26.671411,1.00,50.0,68.0,82.0,255.0
attack,1045.0,80.476555,32.432728,5.00,55.0,77.0,100.0,190.0
defense,1045.0,74.670813,31.259462,5.00,50.0,70.0,90.0,250.0
sp_attack,1045.0,73.031579,32.745857,10.00,50.0,65.0,95.0,194.0
sp_defense,1045.0,72.298565,28.098943,20.00,50.0,70.0,90.0,250.0
speed,1045.0,68.807656,30.210094,5.00,45.0,65.0,90.0,200.0
catch_rate,1027.0,92.739046,75.878404,3.00,45.0,60.0,127.0,255.0
base_friendship,930.0,64.064516,21.452532,0.00,70.0,70.0,70.0,140.0
base_experience,925.0,153.716757,79.283970,36.00,67.0,159.0,201.0,608.0
egg_type_number,1045.0,1.269856,0.450522,0.00,1.0,1.0,2.0,2.0
percentage_male,872.0,54.873853,20.398192,0.00,50.0,50.0,50.0,100.0
egg_cycles,1044.0,31.489464,30.511128,5.00,20.0,20.0,25.0,120.0
against_normal,1045.0,0.868660,0.286863,0.00,1.0,1.0,1.0,1.0
against_fire,1045.0,1.126316,0.714569,0.00,0.5,1.0,2.0,4.0
against_water,1045.0,1.050718,0.609383,0.00,0.5,1.0,1.0,4.0
against_electric,1045.0,1.035646,0.643535,0.00,0.5,1.0,1.0,4.0
against_grass,1045.0,1.001196,0.744350,0.00,0.5,1.0,1.0,4.0
against_ice,1045.0,1.675598,7.685308,0.00,0.5,1.0,2.0,125.0
against_fight,1045.0,1.075120,0.753649,0.00,0.5,1.0,2.0,4.0
against_poison,1045.0,0.953110,0.541238,0.00,0.5,1.0,1.0,4.0
against_ground,1045.0,1.082297,0.782683,0.00,0.5,1.0,1.5,4.0
against_flying,1045.0,1.168900,0.592145,0.25,1.0,1.0,1.0,4.0
against_psychic,1045.0,0.977273,0.501934,0.00,1.0,1.0,1.0,4.0
against_bug,1045.0,0.998086,0.610411,0.00,0.5,1.0,1.0,4.0
against_rock,1045.0,1.238278,0.696560,0.25,1.0,1.0,2.0,4.0
against_ghost,1045.0,1.018660,0.568056,0.00,1.0,1.0,1.0,4.0
against_dragon,1045.0,0.977033,0.375812,0.00,1.0,1.0,1.0,2.0
against_dark,1045.0,1.071053,0.465178,0.25,1.0,1.0,1.0,4.0
against_steel,1045.0,0.981579,0.501753,0.00,0.5,1.0,1.0,4.0
against_fairy,1045.0,1.091148,0.536285,0.00,1.0,1.0,1.0,4.0

## Dataframes filtern

Natürlich sind hier nun einige unsinnigen Variablen dabei, deren "Statistiken" wertlos sind. Dazu gehören die Pokedex Nummern, die Generation, die Typ- oder Fähigkeitsnummern.

Es wäre also sehr praktisch, nur einen *Teil* des DataFrames zu *filtern*, auf den wir dann die Funktion `.describe()` anwenden können.

Mit Hilfe von Pandas bestimmte Spalten eines DataFrames auszuwählen oder über bestimmte Bedingungen auf Zeilenebene zu filtern ist eigentlich sehr einfach. Aber für ein eigentliches Verständnis der ganzen Operationen brauchen wir doch wieder einiges an Hintergrundwissen und damit Exkurse, wie Datenstrukturen in Python generell gefiltert werden, wie ein Pandas DataFrame eigentlich aufgebaut ist, und was das ganze mit dem Modul NumPy zu tun hat.

### Der Aufbau eines Pandas DateFrames

Was vielen Anfängern bei der Benutzung von Pandas DataFrames Schwierigkeiten macht, ist deren Aufbau und damit aber auch die *Rückgabewerte* bei der Filterung. Mit Rückgabewert ist die Art des Objekts gemeint, das bei der Filterung eines DataFrames zurückgegeben wird. Mit der Art des Objektes ändern sich aber auch die Eigenschaften und vor allem die "Dinge", die man mit diesem Objekt machen kann; also wie wir im Exkurs 5: "Methoden und Attribute von Objekten" (Kap. 1.3.2) schon gesehen haben, ändern sich die *Methoden* der Objekte.

Um dies besser zu verstehen, schauen wir uns das am Besten einfach direkt an.

Zu aller erst: **Wie wählt man bestimmte Spalten (und damit Variablen) aus einem Dateframe aus?**

Wir können an den uns längst bekannten `[]`-Operator den Namen einer Spalte als String übergeben.

In [17]:
names = df['name']

names.head()

Index
0        Bulbasaur
1          Ivysaur
2         Venusaur
3    Mega Venusaur
4       Charmander
Name: name, dtype: object

Was wir hier schon sehen können: es wird ein Objekt zurück gegeben, dass einen Index hat (der selbe Index wie im gesamten DataFrame) und einen Namen (hier den Name der Variable - zufälligerweise auch 'name'). Was wir auch bemerken sollten: das ganze sieht nicht wie ein DataFrame-Objekt aus.

Die Python Funktion `type()` kann uns Auskunft über die Art des Objekts geben, wenn wir ihr das Objekt als Argument übergeben.

In [18]:
type(names)

pandas.core.series.Series

Es handelt sich also tatsächlich um kein DataFrame Objekt sondern ein "Pandas Series" Objekt. Was das ist, werden wir gleich noch sehen. Das DataFrame Objekt hat definitiv einen anderen Typ:

In [19]:
type(df)

pandas.core.frame.DataFrame

Was ist aber nun, wenn wir mehrere Spalten/Variablen auswählen wollen, um damit z.B. die `describe()` Funktion aufzurufen? Wir können dem `[]`-Operator eine **Liste** an Namen von Spalten übergeben.

In [20]:
name_vars = ['name', 'german_name', 'japanese_name']

df_all_names = df[name_vars]

df_all_names.head()

                name german_name        japanese_name
Index
0          Bulbasaur     Bisasam  フシギダネ (Fushigidane)
1            Ivysaur   Bisaknosp   フシギソウ (Fushigisou)
2           Venusaur    Bisaflor  フシギバナ (Fushigibana)
3      Mega Venusaur    Bisaflor  フシギバナ (Fushigibana)
4         Charmander    Glumanda      ヒトカゲ (Hitokage)

Die Rückgabe hat auch hier einen Index, aber es fehlt der Name. Ausserdem sieht der Output verdächtig nach einem DataFrame aus. Wir können prüfen, ob dies auch wirklich der Fall ist:

In [21]:
type(df_all_names)

pandas.core.frame.DataFrame

Tatsächlich! Wenn wir **nur eine** Variable eines DataFrames auswählen, dann bekommen wir ein *Pandas Series Objekt* zurück, wenn wir aber **mehrere** Variablen auswählen, dann bekommen wir wieder einen DataFrame mit all seinen Attributen und Methoden zurück. Wie hängt dies zusammen?

Die einzelnen Spalten sind eigentlich einzelne Pandas Series Objekte, die mit einem Index (den Labels der Spalten) verknüpft sind. Was aber ist nun ein Pandas Series Objekt?

### Das Pandas Series Objekt

Wie schon gesagt, baut das Pandas Series Objekt auf dem NumPy Array auf. Ja, man kann sagen, eigentlich ist es nichts anderes, als ein solcher Array, dem allerdings noch ein Index-Attribut und ein Name-Attribut mit auf den Weg gegeben wurde. Beim NumPy Array ist der Index *implizit*, beim Series-Objekt aber *explizit*, so dass man diesen auch *verändern* kann.

Series Objekte erstellt man über die Methode `pd.Series()`.

In [24]:
my_array = np.array([2, 4, 6, 8, 10])

my_series = pd.Series(my_array)

my_series

0     2
1     4
2     6
3     8
4    10
dtype: int64

Wird das Series Objekt ohne explizite Angabe des Indexes erstellt, so wird, wie auch bei Python Listen und bei NumPy Arrays der Index von 0 an hochgezählt.

In [25]:
my_series.index

RangeIndex(start=0, stop=5, step=1)

Da man den Index aber auch explizit angeben kann, kann man ihn auch verändern:

In [26]:
my_series.index = ['a', 'b', 'c', 'd', 'e']

my_series

a     2
b     4
c     6
d     8
e    10
dtype: int64

Zuletzt kann man eben noch einen Namen für das Series Objekt vergeben:

In [27]:
my_series.name = 'even_nums'

my_series

a     2
b     4
c     6
d     8
e    10
Name: even_nums, dtype: int64

Wir können also nun, Schritt für Schritt noch einmal einen DataFrame generieren, indem wir uns zuerst zwei NumPy Arrays erstellen, diese an zwei Pandas Series Objekten übergeben, denen wir den gleichen Index und jeweils einen Namen geben. Diese zwei Series Objekte fügen wir dann zu einem Pandas DataFrame mit der Funktion `pd.concat()` zusammen, wobei wir noch die Achse angeben müssen (wir sagen `concat` also: füge die Series Objekte an der Achse 1, als Spalten aneinander!).

In [28]:
first_array = np.array(["Stefan", "Peter", "Paul", "Maria"])
second_array = np.array([42, 50, 23, 33])

print(type(first_array), "\n")

id_index = ['id012', 'id034', 'id089', 'id120']

print(type(id_index), "\n")

first_series_obj = pd.Series(first_array, index=id_index, name='Vorname')
second_series_obj = pd.Series(second_array, index=id_index, name='Alter')

print(type(first_series_obj), "\n")
print(first_series_obj)

dataframe = pd.concat([first_series_obj, second_series_obj], axis=1)

print(type(dataframe), "\n")

<class 'numpy.ndarray'>

<class 'list'>

<class 'pandas.core.series.Series'>

id012    Stefan
id034     Peter
id089      Paul
id120     Maria
Name: Vorname, dtype: object
<class 'pandas.core.frame.DataFrame'>

In [29]:
dataframe

      Vorname  Alter
id012  Stefan     42
id034   Peter     50
id089    Paul     23
id120   Maria     33

**Beachten Sie aber,** dass das, was wir hier *explizit* der Veranschaulichung halber durchexerzieren, meist *implizit* passiert, wie z.B. ganz am Anfang, als wir die CSV Datei mit Hilfe von `pd.read_csv()` eingelesen haben oder wenn wir einen DataFrame über ein Python Dictionary erstellen:

In [30]:
my_dict = {"Name": ["Maier", "Müller", "Schmidt", "Huber", "Bäcker"],
           "Notenschnitt": [2.75, 2.5, 3.2, 3.8, 1.9],
           "Klasse": [5, 5, 6, 7, 7]}

dataframe_from_dict = pd.DataFrame(my_dict, index=[1, 2, 3, 4, 5])

dataframe_from_dict

      Name  Notenschnitt  Klasse
1    Maier          2.75       5
2   Müller          2.50       5
3  Schmidt          3.20       6
4    Huber          3.80       7
5   Bäcker          1.90       7

In [34]:
# noch ein Beispiel

data = {
    "Name": ["Stefan", "Andrea", "Mike", "Melanie"],
    "Geschlecht": ["m", "w", "d", "w"],
    "Koerpergroesse_cm": [172, 168, 192, 165],
    "Datum": ["2022-02-23", "2022-02-24", pd.NA, "2022-02-28"],
    "Score": [134.7, 162.1, 156.33, 117.9]
}

frame = pd.DataFrame(data)

frame

      Name Geschlecht  Koerpergroesse_cm       Datum   Score
0   Stefan          m                172  2022-02-23  134.70
1   Andrea          w                168  2022-02-24  162.10
2     Mike          d                192        <NA>  156.33
3  Melanie          w                165  2022-02-28  117.90

In [35]:
frame.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Name               4 non-null      object
 1   Geschlecht         4 non-null      object
 2   Koerpergroesse_cm  4 non-null      int64
 3   Datum              3 non-null      object
 4   Score              4 non-null      float64
dtypes: float64(1), int64(1), object(3)
memory usage: 288.0+ bytes

Man kann auch bei der Generierung per Hand schon den Datentyp angeben:

In [32]:
dataframe = pd.DataFrame(
    {
    "Name": pd.Series(["Stefan", "Andrea", "Mike", "Melanie"], dtype="string"),
    "Geschlecht": pd.Series(["m", "w", "d", "w"], dtype="category"),
    "Koerpergroesse_cm": [172, 168, 192, 165],
    "Datum": pd.Series(["2022-02-23", "2022-02-24", pd.NA, "2022-02-28"], dtype="datetime64[ns]"),
    "Score": [134.7, 162.1, 156.33, 117.9]
    }
)

dataframe

      Name Geschlecht  Koerpergroesse_cm      Datum   Score
0   Stefan          m                172 2022-02-23  134.70
1   Andrea          w                168 2022-02-24  162.10
2     Mike          d                192        NaT  156.33
3  Melanie          w                165 2022-02-28  117.90

In [36]:
dataframe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Name               4 non-null      string
 1   Geschlecht         4 non-null      category
 2   Koerpergroesse_cm  4 non-null      int64
 3   Datum              3 non-null      datetime64[ns]
 4   Score              4 non-null      float64
dtypes: category(1), datetime64[ns](1), float64(1), int64(1), string(1)
memory usage: 392.0 bytes

Zusammenfassend ergibt sich folgendes Schaubild für den Zusammenhang zwischen **NumPy Array**, **Pandas Series Objekt** und **Pandas DataFrame**:

![Zusammenhang Pandas Numpy](./img/pandas_numpy_connection.png)

## Filtern mit .loc und .iloc

DataFrames bieten aber eine noch weitere Methode der Filterung. Beim Filtern eines Datensatzes möchte man vielleicht nicht nur explizeit angeben, welche Spaltennamen man filtern möchte, sondern auch eine "Spanne" angeben können; in etwa: "Gib alle Variablen ab Spalte X bis zur Spalte Y aus".

Aber nicht nur das, was ist, wenn man ist, wenn man auf Individuen-, also Zeilenebene filtern möchte. Ein Dataframe besitzt ja schließlich zwei Indices: einen für die Zeilen und einen für die Spalten.

Zu diesem Zweck gibt es die Attribute `.loc` und `.iloc` ("loc" für "location").

In [37]:
df.loc

In [38]:
df.iloc

Dies sind Pandas spezifische Objekte, die jeweils die Indices eines Dataframes vorhalten und auf die per "[lazy Evaluation](https://de.wikipedia.org/wiki/Lazy_Evaluation)" zugegriffen werden kann.

Der Zugriff erfolgt wie bei sämtlichen iterativen Datenstrukturen in Python per `[]`-Operator.

Der Unterschied zwischen `.loc` und `.iloc` ist, dass man `.loc` die Namen der Indices, `.iloc` dagegen die Nummer der einzelnen Indices übergibt (deshalb auch "**i**loc" für "**I**ndex").

Sowohl `.loc` als auch `.iloc` arbeiten mit den üblichen und nun schon bekannten Python **Slicing** Methoden.

Man übergibt sowohl `.loc` als auch `.iloc` über den `[]`-Operator **zwei** Werte, die man mit einem Komma trennt:

1. ein Slicing über die Zeilen, also die Achse 0,
2. ein Slicing über die Spalten, also die Achse 1.

```
<dataframe>.loc[<slicing_0_axis>, <slicing_1_axis>]

<dataframe>.iloc[<slicing_0_axis>, <slicing_1_axis>]
```

Möchte man dabei sagen, dass man **alle** Zeilen, aber nur bestimmte Spalten filtern möchte, so muss man, wie oben bei den Listen gesehen, einen Doppelpunkt `:` im Sinne von: "Nimm als Startindex und Endindex implizit den Anfang und das Ende der Sequent!" übergeben.

Zum besseren Verständnis "bauen" wir uns noch einmal einen übersichtlichen DataFrame, dessen Spalten mit den Zahlen von 1 bis 5 und dessen Zeilen von 'a' bis 'e' indiziert sind. Die Elemente seien entsprechend 'a1', 'a2', 'a3' ... etc.

In [39]:
import string
ascii_list = list(string.ascii_lowercase[:5])
nums = list(range(1, 6))
structure = dict()

for i in nums:
    structure[i] = [c + str(i) for c in ascii_list]
        
structured_df = pd.DataFrame(structure)
structured_df.index = ascii_list
structured_df.columns = nums

structured_df

    1   2   3   4   5
a  a1  a2  a3  a4  a5
b  b1  b2  b3  b4  b5
c  c1  c2  c3  c4  c5
d  d1  d2  d3  d4  d5
e  e1  e2  e3  e4  e5

In [40]:
# filtere die Spalten 2 bis 4

structured_df.loc[:, '2':'4']

    2   3   4
a  a2  a3  a4
b  b2  b3  b4
c  c2  c3  c4
d  d2  d3  d4
e  e2  e3  e4

In [41]:
# das gleich mit .iloc

structured_df.iloc[:, 1:4] # Achtung: das Index, hier wieder halboffenes (!) Intervall

    2   3   4
a  a2  a3  a4
b  b2  b3  b4
c  c2  c3  c4
d  d2  d3  d4
e  e2  e3  e4

In [42]:
# jetzt wollen wir nur die Zeilen b bis d

structured_df.loc['b':'d', :]

    1   2   3   4   5
b  b1  b2  b3  b4  b5
c  c1  c2  c3  c4  c5
d  d1  d2  d3  d4  d5

In [43]:
# dies kann man auch abkürzen

structured_df['b':'d']

    1   2   3   4   5
b  b1  b2  b3  b4  b5
c  c1  c2  c3  c4  c5
d  d1  d2  d3  d4  d5

In [44]:
# und nun wieder das selbe mit .iloc

structured_df.iloc[1:4] # auch hier: halboffenes Intervall!

    1   2   3   4   5
b  b1  b2  b3  b4  b5
c  c1  c2  c3  c4  c5
d  d1  d2  d3  d4  d5

In [45]:
# nun noch eine Kombination aus Zeilen und Spalten
# wir wollen nur die Zeilen d und e und nur die Spalten 1 und 2

structured_df.loc['d':, :'2']

    1   2
d  d1  d2
e  e1  e2

In [46]:
# und mit .iloc

structured_df.iloc[3:, :2]

    1   2
d  d1  d2
e  e1  e2

## Komplexes Filten mit der .filter() Methode

Die `.filter()` Methode gibt uns die Möglichkeit auch komplexeres Filtern auf einen der zwei Indices eines DataFrames anzuwenden. Dabei sind vor allem die zwei Parameter `like=` und `regex=` interessant. Mit dem Parameter `axis=` geben wir an, ob wir über den Zeilenindex (0) oder den Spaltenindex (1) filtern möchten.

So hätten wir oben auf die Spalten, die mit "against" beginnen auch folgendermaßen filtern können:

In [47]:
df.filter(like='against', axis=1)

,against_normal,against_fire,against_water,against_electric,against_grass,against_ice,against_fight,against_poison,against_ground,against_flying,against_psychic,against_bug,against_rock,against_ghost,against_dragon,against_dark,against_steel,against_fairy
Index,,,,,,,,,,,,,,,,,,
0,1.0,2.0,0.5,0.5,0.25,2.0,0.5,1.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5
1,1.0,2.0,0.5,0.5,0.25,2.0,0.5,1.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5
2,1.0,2.0,0.5,0.5,0.25,2.0,0.5,1.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5
3,1.0,1.0,0.5,0.5,0.25,1.0,0.5,1.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5
4,1.0,0.5,2.0,1.0,0.50,0.5,1.0,1.0,2.0,1.0,1.0,0.5,2.0,1.0,1.0,1.0,0.5,0.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1040,1.0,2.0,1.0,1.0,1.00,0.5,2.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,2.0,1.0
1041,0.0,1.0,1.0,1.0,1.00,1.0,0.0,0.5,1.0,1.0,1.0,0.5,1.0,2.0,1.0,2.0,1.0,1.0
1042,1.0,2.0,0.5,0.5,0.50,2.0,0.5,2.0,0.5,2.0,0.5,4.0,1.0,2.0,1.0,2.0,1.0,1.0
1043,1.0,2.0,1.0,1.0,1.00,0.5,1.0,1.0,1.0,1.0,0.5,2.0,2.0,2.0,1.0,2.0,2.0,1.0
1044,0.0,1.0,1.0,1.0,1.00,1.0,0.0,0.5,1.0,1.0,0.5,1.0,1.0,4.0,1.0,4.0,1.0,1.0

Möchten wir nur die "egg types" filtern, so könnten wir schreiben:

In [48]:
df.filter(like='egg', axis=1)

       egg_type_number    egg_type_1 egg_type_2  egg_cycles
Index
0                    2         Grass    Monster        20.0
1                    2         Grass    Monster        20.0
2                    2         Grass    Monster        20.0
3                    2         Grass    Monster        20.0
4                    2        Dragon    Monster        20.0
...                ...           ...        ...         ...
1040                 1  Undiscovered        NaN       120.0
1041                 1  Undiscovered        NaN       120.0
1042                 1  Undiscovered        NaN       120.0
1043                 1  Undiscovered        NaN       120.0
1044                 1  Undiscovered        NaN       120.0

[1045 rows x 4 columns]

Der Parameter `like=` funktioniert dabei wie der Python Operator `in`, mit dem man prüden kann, ob sich eine Subsequenz innerhalb einer anderen Sequenz befindet:

In [49]:
"egg" in "a_egg_type"

True

In [50]:
"egg" in "a_Egg_type"

False

Der `in` Operator und `like=` sind also *case sensitive*, d.h. sie beachten Groß- und Kleinschreibung. Möchten Sie zwischen diesen nicht unterscheiden, so müssten Sie komplexere Muster über RegEx ([Regular Expression](https://de.wikipedia.org/wiki/Regul%C3%A4rer_Ausdruck)) einsetzen.

### ---> Kurzeinführung: Regular Expressions

Bemühen wir noch einmal unseren oben "gebauten" DataFrame `structured_df` und machen uns klar, was es bedeutet, damit sowohl auf Zeilen, als auch auf Spaltenebene *gleichzeitig* zu filtern. `.filter()` kann ja nur ein Achsenelement entgegen nehmen; d.h. man kann nur *entweder* Spalten *oder* Zeilen filtern. Möchte man aber beides gleichzeitig, so muss man `.filter()` *zweimal* anwenden. Entweder durch ein *Zwischenspeichern* in einer Variablen, oder - was manchen eleganter ist - durch das hintereinander Ausführen der `.filter()` Methode durch sog. *chaining*. Man nutzt also den Rückgabewert der einen `.filter()` Methode (was ja nur ein Pandas DataFrame oder Series sein kann) und wendet darauf dann wieder die `.filter()` Methode an.

```
<DataFrame>.filter().filter()
```

Auf diese Weise kann man auch beliebige Methoden (wenn die Rückgabewerte stimmen!) verketten: `<DataFrame>.iloc[<index>].filter(like=<Ausdruck>)`.

In [51]:
# zuerst das Beispiel mit Zwischenspeichern

temp = structured_df.loc[:, '2':'4']

temp.filter(like='b', axis=0)

    2   3   4
b  b2  b3  b4

In [52]:
# das ganze verkettet

structured_df.loc[:, '2':'4'].filter(like='b', axis=0)

    2   3   4
b  b2  b3  b4

## Filtern durch Maskierung

![Japanische Holzmasken](./img/masks.jpg)

<div align="center">&#169; <a href="https://unsplash.com/@finan?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Finan Akbar</a> on <a href="https://unsplash.com/s/photos/japanese-masks?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Unsplash</a></div>
  

Einzelne Zeilen und Spalten zu filtern können wir nun. Allerdings filtern wir immer nur auf die *ganze* Zeile, oder *ganze* Spalte. Was ist aber, wenn wir bestimmte *Bedingungen* für das Filtern angeben wollen, z.B. "gib mir alle Pokemon, deren Gewicht kleiner/größer X ist" oder "gib mir nur die Pokemon vom Typ 'water'", oder was ist, wenn ich sagen will "gib mir genau das Pokemon mit der Pokedexnummer X oder dem Namen Y"? Das bedeutet also, wir wollen die Fähigkeit haben, innerhalb von Variablen nach bestimmten Bedingungen zu filtern und nur die Einträge "übrig zu lassen", bei denen die Bedingung "wahr" oder in Python-Sprache `True` ist.

Da es sich bei den Variablen (Spalten) um Pandas Series handelt und diese wiederum angereicherte NumPy Arrays, kann man mit ihnen auch arbeiten, wie mit NumPy Arrays. Solche Arrays kann man einem gewöhnlichen *konditionalen Operator* in Python übergeben und NumPy prüft dann die Bedingung auf *jedes* Element im Array.

In Python existieren folgende Vergleichsoperatoren:

| Operator | Bedeutung |
|:---:|:---|
| `==` | ist gleich |
| `!=` | ist ungleich |
| `>` | ist grösser |
| `<` | ist kleiner |
| `>=` | ist grösser oder gleich |
| `<=` | ist kleiner oder gleich |

Anstelle des Python `in` Operators kann die `.isin()` Methode verwendet werden.

In [53]:
nums = pd.Series([23, 34, 43, 44, 67, 78, 88, 90])

nums < 67

0     True
1     True
2     True
3     True
4    False
5    False
6    False
7    False
dtype: bool

In [54]:
nums >= 78

0    False
1    False
2    False
3    False
4    False
5     True
6     True
7     True
dtype: bool

In [55]:
nums % 2 != 0

0     True
1    False
2     True
3    False
4     True
5    False
6    False
7    False
dtype: bool

In [56]:
nums.isin([34, 44, 78, 88])

0    False
1     True
2    False
3     True
4    False
5     True
6     True
7    False
dtype: bool

In [57]:
nums.isin(range(40, 71))

0    False
1    False
2     True
3     True
4     True
5    False
6    False
7    False
dtype: bool

Diese **Masken** an `True` und `False` Werten können wir nun benutzen, um unseren DataFrame zu filtern. Wir können diese Maske nun an den `[]`-Operator übergeben. Jede Zeile, die dann so einen `False` Wert hat wird ausgeblendet, alle anderen Zeilen werden behalten.

![Schaubild Maskierung](./img/pandas_masking.png)

In [58]:
# alle Pokemon, die schwerer als 900 Kg sind

greater_900kg = df['weight_kg'] > 900

df[greater_900kg]

,pokedex_number,name,german_name,japanese_name,generation,status,species,type_number,type_1,type_2,height_m,weight_kg,abilities_number,ability_1,ability_2,ability_hidden,total_points,hp,attack,defense,sp_attack,sp_defense,speed,catch_rate,base_friendship,base_experience,growth_rate,egg_type_number,egg_type_1,egg_type_2,percentage_male,egg_cycles,against_normal,against_fire,against_water,against_electric,against_grass,against_ice,against_fight,against_poison,against_ground,against_flying,against_psychic,against_bug,against_rock,against_ghost,against_dragon,against_dark,against_steel,against_fairy
Index,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
451,376,Mega Metagross,Metagross,メタグロス (Metagross),3,Normal,Iron Leg Pokémon,2,Steel,Psychic,2.5,942.9,1,Tough Claws,NaN,NaN,700,80,145,150,105,110,110,3.0,35.0,315.0,Slow,1,Mineral,NaN,NaN,40.0,0.5,2.0,1.0,1.0,0.50,0.5,1.0,0.0,2.0,0.5,0.25,1.00,0.5,2.0,0.5,2.0,0.5,0.5
461,383,Groudon,Groudon,グラードン (Groudon),3,Legendary,Continent Pokémon,1,Ground,NaN,3.5,950.0,1,Drought,NaN,NaN,670,100,150,140,100,90,90,3.0,0.0,302.0,Slow,1,Undiscovered,NaN,NaN,120.0,1.0,1.0,2.0,0.0,2.00,2.0,1.0,0.5,1.0,1.0,1.00,1.00,0.5,1.0,1.0,1.0,1.0,1.0
462,383,Primal Groudon,Groudon,グラードン (Groudon),3,Legendary,Continent Pokémon,2,Ground,Fire,5.0,999.7,1,Desolate Land,NaN,NaN,770,100,180,160,150,90,90,5.0,0.0,347.0,Slow,1,Undiscovered,NaN,NaN,120.0,1.0,0.5,0.0,0.0,1.00,1.0,1.0,0.5,2.0,1.0,1.00,0.50,1.0,1.0,1.0,1.0,0.5,0.5
882,750,Mudsdale,Pampross,バンバドロ (Banbadoro),7,Normal,Draft Horse Pokémon,1,Ground,NaN,2.5,920.0,3,Own Tempo,Stamina,Inner Focus,500,100,125,100,55,85,35,60.0,70.0,175.0,Medium Fast,1,Field,NaN,50.0,20.0,1.0,1.0,2.0,0.0,2.00,2.0,1.0,0.5,1.0,1.0,1.00,1.00,0.5,1.0,1.0,1.0,1.0,1.0
923,790,Cosmoem,Cosmovum,コスモウム (Cosmovum),7,Legendary,Protostar Pokémon,1,Psychic,NaN,0.1,999.9,1,Sturdy,NaN,NaN,400,43,29,131,29,131,37,45.0,0.0,140.0,Slow,1,Undiscovered,NaN,NaN,120.0,1.0,1.0,1.0,1.0,1.00,1.0,0.5,1.0,1.0,1.0,0.50,2.00,1.0,2.0,1.0,2.0,1.0,1.0
930,797,Celesteela,Kaguron,テッカグヤ (Tekkaguya),7,Sub Legendary,Launch Pokémon,2,Steel,Flying,9.2,999.9,1,Beast Boost,NaN,NaN,570,97,101,103,107,101,61,45.0,0.0,257.0,Slow,1,Undiscovered,NaN,NaN,120.0,0.5,2.0,1.0,2.0,0.25,1.0,1.0,0.0,0.0,0.5,0.50,0.25,1.0,1.0,0.5,1.0,0.5,0.5
1032,890,Eternatus,Endynalos,ムゲンダイナ (Mugendina),8,Legendary,Gigantic Pokémon,2,Poison,Dragon,20.0,950.0,1,Pressure,NaN,NaN,690,140,85,95,145,95,130,255.0,NaN,NaN,Slow,1,Undiscovered,NaN,NaN,120.0,1.0,0.5,0.5,0.5,0.25,2.0,0.5,0.5,2.0,1.0,2.00,0.50,1.0,1.0,2.0,1.0,1.0,1.0

In [59]:
# wähle ein zufälliges Pokemon aus

random_pokedex_num = np.random.randint(1, 898) # generiere eine zufällige Ganzzahl zwischen 1 und 898

random_pokemon = df['pokedex_number'] == random_pokedex_num

df[random_pokemon]

,pokedex_number,name,german_name,japanese_name,generation,status,species,type_number,type_1,type_2,height_m,weight_kg,abilities_number,ability_1,ability_2,ability_hidden,total_points,hp,attack,defense,sp_attack,sp_defense,speed,catch_rate,base_friendship,base_experience,growth_rate,egg_type_number,egg_type_1,egg_type_2,percentage_male,egg_cycles,against_normal,against_fire,against_water,against_electric,against_grass,against_ice,against_fight,against_poison,against_ground,against_flying,against_psychic,against_bug,against_rock,against_ghost,against_dragon,against_dark,against_steel,against_fairy
Index,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
492,409,Rampardos,Rameidon,ラムパルド (Rampald),4,Normal,Head Butt Pokémon,1,Rock,NaN,1.6,102.5,2,Mold Breaker,NaN,Sheer Force,495,97,165,60,65,50,58,45.0,70.0,173.0,Erratic,1,Monster,NaN,87.5,30.0,0.5,0.5,2.0,1.0,2.0,1.0,2.0,0.5,2.0,0.5,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0

### Logische Kombinatoren

Möchte man mehrere Bedingungem in unterschiedlichen Variablen prüfen, so kann man die Masken der Prüfungen mit den Logischen Operatoren "und" (`&`), "oder" (`|`) und "nicht" (`~`) kombinieren.

So kann man z.B. filtern auf alle "mythical" Pokemon, die als zweiten Typ "psychic" haben; oder alle Pokemon, die entweder vom Typ "steel" sind, oder einen Attacke Wert größer 150 haben; oder alle Pokemon, die *nicht* als Status "normal" haben.

In [60]:
# mythical Pokemon, die "psychic" als Type_2 haben

mythical = df['status'] == 'Mythical'
psych_t2 = df['type_2'] == 'Psychic'

df[mythical & psych_t2]

,pokedex_number,name,german_name,japanese_name,generation,status,species,type_number,type_1,type_2,height_m,weight_kg,abilities_number,ability_1,ability_2,ability_hidden,total_points,hp,attack,defense,sp_attack,sp_defense,speed,catch_rate,base_friendship,base_experience,growth_rate,egg_type_number,egg_type_1,egg_type_2,percentage_male,egg_cycles,against_normal,against_fire,against_water,against_electric,against_grass,against_ice,against_fight,against_poison,against_ground,against_flying,against_psychic,against_bug,against_rock,against_ghost,against_dragon,against_dark,against_steel,against_fairy
Index,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
465,385,Jirachi,Jirachi,ジラーチ (Jirachi),3,Mythical,Wish Pokémon,2,Steel,Psychic,0.3,1.1,1,Serene Grace,NaN,NaN,600,100,100,100,100,100,100,3.0,100.0,270.0,Slow,1,Undiscovered,NaN,NaN,120.0,0.5,2.0,1.0,1.0,0.5,0.5,1.0,0.0,2.0,0.5,0.25,1.0,0.5,2.0,0.5,2.0,0.5,0.5
759,648,Meloetta Aria Forme,Meloetta,メロエッタ (Meloetta),5,Mythical,Melody Pokémon,2,Normal,Psychic,0.6,6.5,1,Serene Grace,NaN,NaN,600,100,77,77,128,128,90,3.0,100.0,270.0,Slow,1,Undiscovered,NaN,NaN,120.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.50,2.0,1.0,0.0,1.0,2.0,1.0,1.0

In [61]:
# entweder type_1 'steel' oder attack > 150

steel_t1 = df['type_1'] == 'Steel'
attack_gt_150 = df['attack'] > 150

df[steel_t1 | attack_gt_150]

,pokedex_number,name,german_name,japanese_name,generation,status,species,type_number,type_1,type_2,height_m,weight_kg,abilities_number,ability_1,ability_2,ability_hidden,total_points,hp,attack,defense,sp_attack,sp_defense,speed,catch_rate,base_friendship,base_experience,growth_rate,egg_type_number,egg_type_1,egg_type_2,percentage_male,egg_cycles,against_normal,against_fire,against_water,against_electric,against_grass,against_ice,against_fight,against_poison,against_ground,against_flying,against_psychic,against_bug,against_rock,against_ghost,against_dragon,against_dark,against_steel,against_fairy
Index,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
69,52,Galarian Meowth,Mauzi,ニャース (Nyarth),1,Normal,Scratch Cat Pokémon,1,Steel,NaN,0.4,7.5,3,Pickup,Tough Claws,Unnerve,290,50,65,55,40,40,40,NaN,NaN,NaN,Medium Fast,1,Field,NaN,NaN,20.0,0.50,2.0,1.0,1.0,0.50,0.50,2.00,0.0,2.0,0.50,0.50,0.50,0.50,1.0,0.5,1.0,0.5,0.5
164,127,Mega Pinsir,Pinsir,カイロス (Kailios),1,Normal,Stag Beetle Pokémon,2,Bug,Flying,1.7,59.0,1,Aerilate,NaN,NaN,600,65,155,120,65,90,105,45.0,70.0,210.0,Slow,1,Bug,NaN,50.0,25.0,1.00,2.0,1.0,2.0,0.25,2.00,0.25,1.0,0.0,2.00,1.00,0.50,4.00,1.0,1.0,1.0,1.0,1.0
168,130,Mega Gyarados,Garados,ギャラドス (Gyarados),1,Normal,Atrocious Pokémon,2,Water,Dark,6.5,305.0,1,Mold Breaker,NaN,NaN,640,95,155,109,70,130,81,45.0,70.0,224.0,Slow,2,Dragon,Water 2,50.0,5.0,1.00,0.5,0.5,2.0,2.00,0.50,2.00,1.0,1.0,1.00,0.00,2.00,1.00,0.5,1.0,0.5,0.5,2.0
194,150,Mega Mewtwo X,Mewtu,ミュウツー (Mewtwo),1,Legendary,Genetic Pokémon,2,Psychic,Fighting,2.3,127.0,1,Steadfast,NaN,NaN,780,106,190,100,154,100,130,3.0,0.0,351.0,Slow,1,Undiscovered,NaN,NaN,120.0,1.00,1.0,1.0,1.0,1.00,1.00,0.50,1.0,1.0,2.00,1.00,1.00,0.50,2.0,1.0,1.0,1.0,2.0
255,208,Steelix,Stahlos,ハガネール (Haganeil),2,Normal,Iron Snake Pokémon,2,Steel,Ground,9.2,400.0,3,Rock Head,Sturdy,Sheer Force,510,75,85,200,55,65,30,25.0,70.0,179.0,Medium Fast,1,Mineral,NaN,50.0,25.0,0.50,2.0,2.0,0.0,1.00,1.00,2.00,0.0,2.0,0.50,0.50,0.50,0.25,1.0,0.5,1.0,0.5,0.5
256,208,Mega Steelix,Stahlos,ハガネール (Haganeil),2,Normal,Iron Snake Pokémon,2,Steel,Ground,10.5,740.0,1,Sand Force,NaN,NaN,610,75,125,230,55,95,30,25.0,70.0,214.0,Medium Fast,1,Mineral,NaN,50.0,25.0,0.50,2.0,2.0,0.0,1.00,1.00,2.00,0.0,2.0,0.50,0.50,0.50,0.25,1.0,0.5,1.0,0.5,0.5
264,214,Mega Heracross,Skaraborn,ヘラクロス (Heracros),2,Normal,Single Horn Pokémon,2,Bug,Fighting,1.7,62.5,1,Skill Link,NaN,NaN,600,80,185,115,40,105,75,45.0,70.0,210.0,Slow,1,Bug,NaN,50.0,25.0,1.00,2.0,1.0,1.0,0.50,1.00,0.50,1.0,0.5,4.00,2.00,0.50,1.00,1.0,1.0,0.5,1.0,2.0
278,227,Skarmory,Panzaeron,エアームド (Airmd),2,Normal,Armor Bird Pokémon,2,Steel,Flying,1.7,50.5,3,Keen Eye,Sturdy,Weak Armor,465,65,80,140,40,70,70,25.0,70.0,163.0,Slow,1,Flying,NaN,50.0,25.0,0.50,2.0,1.0,2.0,0.25,1.00,1.00,0.0,0.0,0.50,0.50,0.25,1.00,1.0,0.5,1.0,0.5,0.5
301,248,Mega Tyranitar,Despotar,バンギラス (Bangiras),2,Normal,Armor Pokémon,2,Rock,Dark,2.5,255.0,1,Sand Stream,NaN,NaN,700,100,164,150,95,120,71,45.0,35.0,315.0,Slow,1,Monster,NaN,50.0,40.0,0.50,0.5,2.0,1.0,2.00,1.00,4.00,0.5,2.0,0.50,0.00,2.00,1.00,0.5,1.0,0.5,2.0,2.0
312,257,Mega Blaziken,Lohgock,バシャーモ (Bursyamo),3,Normal,Blaze Pokémon,2,Fire,Fighting,1.9,52.0,1,Speed Boost,NaN,NaN,630,80,160,80,130,80,100,45.0,70.0,284.0,Medium Slow,1,Field,NaN,87.5,20.0,1.00,0.5,2.0,1.0,0.50,0.50,1.00,1.0,2.0,2.00,2.00,0.25,1.00,1.0,1.0,0.5,0.5,1.0
348,289,Slaking,Letarking,ケッキング (Kekking),3,Normal,Lazy Pokémon,1,Normal,NaN,2.0,130.5,1,Truant,NaN,NaN,670,150,160,100,95,65,100,45.0,70.0,252.0,Slow,1,Field,NaN,50.0,15.0,1.00,1.0,1.0,1.0,1.00,1.00,2.00,1.0,1.0,1.00,1.00,1.00,1.00,0.0,1.0,1.0,1.0,1.0
363,303,Mawile,Flunkifer,クチート (Kucheat),3,Normal,Deceiver Pokémon,2,Steel,Fairy,0.6,11.5,3,Hyper Cutter,Intimidate,Sheer Force,380,50,85,85,55,55,50,45.0,70.0,133.0,Fast,2,Fairy,Field,50.0,20.0,0.50,2.0,1.0,1.0,0.50,0.50,1.00,0.0,2.0,0.50,0.50,0.25,0.50,1.0,0.0,0.5,1.0,0.5
364,303,Mega Mawile,Flunkifer,クチート (Kucheat),3,Normal,Deceiver Pokémon,2,Steel,Fairy,1.0,23.5,1,Huge Power,NaN,NaN,480,50,105,125,55,95,50,45.0,70.0,168.0,Fast,2,Fairy,Field,50.0,20.0,0.50,2.0,1.0,1.0,0.50,0.50,1.00,0.0,2.0,0.50,0.50,0.25,0.50,1.0,0.0,0.5,1.0,0.5
365,304,Aron,Stollunior,ココドラ (Cokodora),3,Normal,Iron Armor Pokémon,2,Steel,Rock,0.4,60.0,3,Sturdy,Rock Head,Heavy Metal,330,50,70,100,40,40,30,180.0,35.0,66.0,Slow,1,Monster,NaN,50.0,35.0,0.25,1.0,2.0,1.0,1.00,0.50,4.00,0.0,4.0,0.25,0.50,0.50,0.50,1.0,0.5,1.0,1.0,0.5
366,305,Lairon,Stollrak,コドラ (Kodora),3,Normal,Iron Armor Pokémon,2,Steel,Rock,0.9,120.0,3,Sturdy,Rock Head,Heavy Metal,430,60,90,140,50,50,40,90.0,35.0,151.0,Slow,1,Monster,NaN,50.0,35.0,0.25,1.0,2.0,1.0,1.00,0.50,4.00,0.0,4.0,0.25,0.50,0.50,0.50,1.0,0.5,1.0,1.0,0.5
367,306,Aggron,Stolloss,ボスゴドラ (Bossgodora),3,Normal,Iron Armor Pokémon,2,Steel,Rock,2.1,360.0,3,Sturdy,Rock Head,Heavy Metal,530,70,110,180,60,60,50,45.0,35.0,239.0,Slow,1,Monster,NaN,50.0,35.0,0.25,1.0,2.0,1.0,1.00,0.50,4.00,0.0,4.0,0.25,0.50,0.50,0.50,1.0,0.5,1.0,1.0,0.5
368,306,Mega Aggron,Stolloss,ボスゴドラ (Bossgodora),3,Normal,Iron Armor Pokémon,1,Steel,NaN,2.2,395.0,1,Filter,NaN,NaN,630,70,140,230,60,80,50,45.0,35.0,284.0,Slow,1,Monster,NaN,50.0,35.0,0.50,1.5,1.0,1.0,0.50,0.50,1.50,0.0,1.5,0.50,0.50,0.50,0.50,1.0,0.5,1.0,0.5,0.5
425,354,Mega Banette,Banette,ジュペッタ (Juppeta),3,Normal,Marionette Pokémon,1,Ghost,NaN,1.2,13.0,1,Prankster,NaN,NaN,555,64,165,75,93,83,75,45.0,35.0,194.0,Fast,1,Amorphous,NaN,50.0,25.0,0.00,1.0,1.0,1.0,1.00,1.00,0.00,0.5,1.0,1.00,1.00,0.50,1.00,2.0,1.0,2.0,1.0,1.0
448,374,Beldum,Tanhel,ダンバル (Dumbber),3,Normal,Iron Ball Pokémon,2,Steel,Psychic,0.6,95.2,2,Clear Body,NaN,Light Metal,300,40,55,80,35,60,30,3.0,35.0,60.0,Slow,1,Mineral,NaN,NaN,40.0,0.50,2.0,1.0,1.0,0.50,0.50,1.00,0.0,2.0,0.50,0.25,1.00,0.50,2.0,0.5,2.0,0.5,0.5
449,375,Metang,Metang,メタング (Metang),3,Normal,Iron Claw Pokémon,2,Steel,Psychic,1.2,202.5,2,Clear Body,NaN,Light Metal,420,60,75,100,55,80,50,3.0,35.0,147.0,Slow,1,Mineral,NaN,NaN,40.0,0.50,2.0,1.0,1.0,0.50,0.50,1.00,0.0,2.0,0.50,0.25,1.00,0.50,2.0,0.5,2.0,0.5,0.5
450,376,Metagross,Metagross,メタグロス (Metagross),3,Normal,Iron Leg Pokémon,2,Steel,Psychic,1.6,550.0,2,Clear Body,NaN,Light Metal,600,80,135,130,95,90,70,3.0,35.0,270.0,Slow,1,Mineral,NaN,NaN,40.0,0.50,2.0,1.0,1.0,0.50,0.50,1.00,0.0,2.0,0.50,0.25,1.00,0.50,2.0,0.5,2.0,0.5,0.5
451,376,Mega Metagross,Metagross,メタグロス (Metagross),3,Normal,Iron Leg Pokémon,2,Steel,Psychic,2.5,942.9,1,Tough Claws,NaN,NaN,700,80,145,150,105,110,110,3.0,35.0,315.0,Slow,1,Mineral,NaN,NaN,40.0,0.50,2.0,1.0,1.0,0.50,0.50,1.00,0.0,2.0,0.50,0.25,1.00,0.50,2.0,0.5,2.0,0.5,0.5
454,379,Registeel,Registeel,レジスチル (Registeel),3,Sub Legendary,Iron Pokémon,1,Steel,NaN,1.9,205.0,2,Clear Body,NaN,Light Metal,580,80,75,150,75,150,50,3.0,35.0,261.0,Slow,1,Undiscovered,NaN,NaN,80.0,0.50,2.0,1.0,1.0,0.50,0.50,2.00,0.0,2.0,0.50,0.50,0.50,0.50,1.0,0.5,1.0,0.5,0.5
462,383,Primal Groudon,Groudon,グラードン (Groudon),3,Legendary,Continent Pokémon,2,Ground,Fire,5.0,999.7,1,Desolate Land,NaN,NaN,770,100,180,160,150,90,90,5.0,0.0,347.0,Slow,1,Undiscovered,NaN,NaN,120.0,1.00,0.5,0.0,0.0,1.00,1.00,1.00,0.5,2.0,1.00,1.00,0.50,1.00,1.0,1.0,1.0,0.5,0.5
464,384,Mega Rayquaza,Rayquaza,レックウザ (Rayquaza),3,Legendary,Sky High Pokémon,2,Dragon,Flying,10.8,392.0,1,Delta Stream,NaN,NaN,780,105,180,100,180,100,115,3.0,0.0,351.0,Slow,1,Undiscovered,NaN,NaN,120.0,1.00,0.5,0.5,0.5,0.25,2.00,0.50,1.0,0.0,1.00,1.00,0.50,1.00,1.0,2.0,1.0,1.0,2.0
465,385,Jirachi,Jirachi,ジラーチ (Jirachi),3,Mythical,Wish Pokémon,2,Steel,Psychic,0.3,1.1,1,Serene Grace,NaN,NaN,600,100,100,100,100,100,100,3.0,100.0,270.0,Slow,1,Undiscovered,NaN,NaN,120.0,0.50,2.0,1.0,1.0,0.50,0.50,1.00,0.0,2.0,0.50,0.25,1.00,0.50,2.0,0.5,2.0,0.5,0.5
467,386,Deoxys Attack Forme,Deoxys,デオキシス (Deoxys),3,Mythical,DNA Pokémon,1,Psychic,NaN,1.7,60.8,1,Pressure,NaN,NaN,600,50,180,20,180,20,150,3.0,0.0,270.0,Slow,1,Undiscovered,NaN,NaN,120.0,1.00,1.0,1.0,1.0,1.00,1.00,0.50,1.0,1.0,1.00,0.50,2.00,1.00,2.0,1.0,2.0,1.0,1.0
492,409,Rampardos,Rameidon,ラムパルド (Rampald),4,Normal,Head Butt Pokémon,1,Rock,NaN,1.6,102.5,2,Mold Breaker,NaN,Sheer Force,495,97,165,60,65,50,58,45.0,70.0,173.0,Erratic,1,Monster,NaN,87.5,30.0,0.50,0.5,2.0,1.0,2.00,1.00,2.00,0.5,2.0,0.50,1.00,1.00,1.00,1.0,1.0,1.0,2.0,1.0
522,436,Bronzor,Bronzel,ドーミラー (Dohmirror),4,Normal,Bronze Pokémon,2,Steel,Psychic,0.5,60.5,3,Levitate,Heatproof,Heavy Metal,300,57,24,86,24,86,23,255.0,70.0,60.0,Medium Fast,1,Mineral,NaN,NaN,20.0,0.50,2.0,1.0,1.0,0.50,0.50,1.00,0.0,0.0,0.50,0.25,1.00,0.50,2.0,0.5,2.0,0.5,0.5
523,437,Bronzong,Bronzong,ドータクン (Dohtakun),4,Normal,Bronze Bell Pokémon,2,Steel,Psychic,1.3,187.0,3,Levitate,Heatproof,Heavy Metal,500,67,89,116,79,116,33,90.0,70.0,175.0,Medium Fast,1,Mineral,NaN,NaN,20.0,0.50,2.0,1.0,1.0,0.50,0.50,1.00,0.0,0.0,0.50,0.25,1.00,0.50,2.0,0.5,2.0,0.5,0.5
532,445,Mega Garchomp,Knakrack,ガブリアス (Gaburias),4,Normal,Mach Pokémon,2,Dragon,Ground,1.9,95.0,1,Sand Force,NaN,NaN,700,108,170,115,120,95,92,45.0,70.0,315.0,Slow,2,Dragon,Monster,50.0,40.0,1.00,0.5,1.0,0.0,1.00,4.00,1.00,0.5,1.0,1.00,1.00,1.00,0.50,1.0,2.0,1.0,1.0,2.0
565,475,Mega Gallade,Galagladi,エルレイド (Erureido),4,Normal,Blade Pokémon,2,Psychic,Fighting,1.6,56.4,1,Inner Focus,NaN,NaN,618,68,165,95,65,115,110,45.0,35.0,278.0,Slow,1,Amorphous,NaN,100.0,20.0,1.00,1.0,1.0,1.0,1.00,1.00,0.50,1.0,1.0,2.00,1.00,1.00,0.50,2.0,1.0,1.0,1.0,2.0
578,483,Dialga,Dialga,ディアルガ (Dialga),4,Legendary,Temporal Pokémon,2,Steel,Dragon,5.4,683.0,2,Pressure,NaN,Telepathy,680,100,120,120,150,100,90,3.0,0.0,306.0,Slow,1,Undiscovered,NaN,NaN,120.0,0.50,1.0,0.5,0.5,0.25,1.00,2.00,0.0,2.0,0.50,0.50,0.50,0.50,1.0,1.0,1.0,0.5,1.0
581,486,Regigigas,Regigigas,レジギガス (Regigigas),4,Sub Legendary,Colossal Pokémon,1,Normal,NaN,3.7,420.0,1,Slow Start,NaN,NaN,670,110,160,110,80,110,100,3.0,0.0,302.0,Slow,1,Undiscovered,NaN,NaN,120.0,1.00,1.0,1.0,1.0,1.00,1.00,2.00,1.0,1.0,1.00,1.00,1.00,1.00,0.0,1.0,1.0,1.0,1.0
658,555,Galarian Darmanitan Zen Mode,Flampivian,ヒヒダルマ (Hihidaruma),5,Normal,Zen Charm Pokémon,2,Ice,Fire,1.7,120.0,2,Gorilla Tactics,NaN,Zen Mode,540,105,160,55,30,55,135,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,1.00,1.0,2.0,1.0,0.50,0.25,2.00,1.0,2.0,1.00,1.00,0.50,4.00,1.0,1.0,1.0,1.0,0.5
703,599,Klink,Klikk,ギアル (Giaru),5,Normal,Gear Pokémon,1,Steel,NaN,0.3,21.0,3,Plus,Minus,Clear Body,300,40,55,70,45,60,30,130.0,70.0,60.0,Medium Slow,1,Mineral,NaN,NaN,20.0,0.50,2.0,1.0,1.0,0.50,0.50,2.00,0.0,2.0,0.50,0.50,0.50,0.50,1.0,0.5,1.0,0.5,0.5
704,600,Klang,Kliklak,ギギアル (Gigiaru),5,Normal,Gear Pokémon,1,Steel,NaN,0.6,51.0,3,Plus,Minus,Clear Body,440,60,80,95,70,85,50,60.0,70.0,154.0,Medium Slow,1,Mineral,NaN,NaN,20.0,0.50,2.0,1.0,1.0,0.50,0.50,2.00,0.0,2.0,0.50,0.50,0.50,0.50,1.0,0.5,1.0,0.5,0.5
705,601,Klinklang,Klikdiklak,ギギギアル (Gigigiaru),5,Normal,Gear Pokémon,1,Steel,NaN,0.6,81.0,3,Plus,Minus,Clear Body,520,60,100,115,70,85,90,30.0,70.0,234.0,Medium Slow,1,Mineral,NaN,NaN,20.0,0.50,2.0,1.0,1.0,0.50,0.50,2.00,0.0,2.0,0.50,0.50,0.50,0.50,1.0,0.5,1.0,0.5,0.5
743,638,Cobalion,Kobalium,コバルオン (Cobalon),5,Sub Legendary,Iron Will Pokémon,2,Steel,Fighting,2.1,250.0,1,Justified,NaN,NaN,580,91,90,129,90,72,108,3.0,35.0,261.0,Slow,1,Undiscovered,NaN,NaN,80.0,0.50,2.0,1.0,1.0,0.50,0.50,2.00,0.0,2.0,1.00,1.00,0.25,0.25,1.0,0.5,0.5,0.5,1.0
755,646,Black Kyurem,Kyurem,キュレム (Kyurem),5,Legendary,Boundary Pokémon,2,Dragon,Ice,3.3,325.0,1,Teravolt,NaN,NaN,700,125,170,100,120,90,95,3.0,0.0,315.0,Slow,1,Undiscovered,NaN,NaN,120.0,1.00,1.0,0.5,0.5,0.50,1.00,2.00,1.0,1.0,1.00,1.00,1.00,2.00,1.0,2.0,1.0,2.0,2.0
793,679,Honedge,Gramokles,ヒトツキ (Hitotsuki),6,Normal,Sword Pokémon,2,Steel,Ghost,0.8,2.0,1,No Guard,NaN,NaN,325,45,80,100,35,37,28,180.0,70.0,65.0,Medium Fast,1,Mineral,NaN,50.0,20.0,0.00,2.0,1.0,1.0,0.50,0.50,0.00,0.0,2.0,0.50,0.50,0.25,0.50,2.0,0.5,2.0,0.5,0.5
794,680,Doublade,Duokles,ニダンギル (Nidangill),6,Normal,Sword Pokémon,2,Steel,Ghost,0.8,4.5,1,No Guard,NaN,NaN,448,59,110,150,45,49,35,90.0,70.0,157.0,Medium Fast,1,Mineral,NaN,50.0,20.0,0.00,2.0,1.0,1.0,0.50,0.50,0.00,0.0,2.0,0.50,0.50,0.25,0.50,2.0,0.5,2.0,0.5,0.5
795,681,Aegislash Blade Forme,Durengard,ギルガルド (Gillgard),6,Normal,Royal Sword Pokémon,2,Steel,Ghost,1.7,53.0,1,Stance Change,NaN,NaN,520,60,150,50,150,50,60,45.0,70.0,234.0,Medium Fast,1,Mineral,NaN,50.0,20.0,0.00,2.0,1.0,1.0,0.50,0.50,0.00,0.0,2.0,0.50,0.50,0.25,0.50,2.0,0.5,2.0,0.5,0.5
796,681,Aegislash Shield Forme,Durengard,ギルガルド (Gillgard),6,Normal,Royal Sword Pokémon,2,Steel,Ghost,1.7,53.0,1,Stance Change,NaN,NaN,520,60,50,150,50,150,60,45.0,70.0,234.0,Medium Fast,1,Mineral,NaN,50.0,20.0,0.00,2.0,1.0,1.0,0.50,0.50,0.00,0.0,2.0,0.50,0.50,0.25,0.50,2.0,0.5,2.0,0.5,0.5
822,707,Klefki,Clavion,クレッフィ (Cleffy),6,Normal,Key Ring Pokémon,2,Steel,Fairy,0.2,3.0,2,Prankster,NaN,Magician,470,57,80,91,80,87,75,75.0,70.0,165.0,Fast,1,Mineral,NaN,50.0,20.0,0.50,2.0,1.0,1.0,0.50,0.50,1.00,0.0,2.0,0.50,0.50,0.25,0.50,1.0,0.0,0.5,1.0,0.5
843,719,Mega Diancie,Diancie,ディアンシー (Diancie),6,Mythical,Jewel Pokémon,2,Rock,Fairy,1.1,27.8,1,Magic Bounce,NaN,NaN,700,50,160,110,160,110,110,3.0,70.0,315.0,Slow,1,Undiscovered,NaN,NaN,25.0,0.50,0.5,2.0,1.0,2.00,1.00,1.00,1.0,2.0,0.50,1.00,0.50,1.00,1.0,0.0,0.5,4.0,1.0
845,720,Hoopa Hoopa Unbound,Hoopa,フーパ (Hoopa),6,Mythical,Djinn Pokémon,2,Psychic,Dark,6.5,490.0,1,Magician,NaN,NaN,680,80,160,60,170,130,80,3.0,100.0,306.0,Slow,1,Undiscovered,NaN,NaN,120.0,1.00,1.0,1.0,1.0,1.00,1.00,1.00,1.0,1.0,1.00,0.00,4.00,1.00,1.0,1.0,1.0,1.0,2.0
930,797,Celesteela,Kaguron,テッカグヤ (Tekkaguya),7,Sub Legendary,Launch Pokémon,2,Steel,Flying,9.2,999.9,1,Beast Boost,NaN,NaN,570,97,101,103,107,101,61,45.0,0.0,257.0,Slow,1,Undiscovered,NaN,NaN,120.0,0.50,2.0,1.0,2.0,0.25,1.00,1.00,0.0,0.0,0.50,0.50,0.25,1.00,1.0,0.5,1.0,0.5,0.5
931,798,Kartana,Katagami,カミツルギ (Kamiturugi),7,Sub Legendary,Drawn Sword Pokémon,2,Grass,Steel,0.3,0.1,1,Beast Boost,NaN,NaN,570,59,181,131,59,31,109,45.0,0.0,257.0,Slow,1,Undiscovered,NaN,NaN,120.0,0.50,4.0,0.5,0.5,0.25,1.00,2.00,0.0,1.0,1.00,0.50,1.00,0.50,1.0,0.5,1.0,0.5,0.5
934,800,Dusk Mane Necrozma,Necrozma,ネクロズマ (Necrozma),7,Legendary,Prism Pokémon,2,Psychic,Steel,3.8,460.0,1,Prism Armor,NaN,NaN,680,97,157,127,113,109,77,3.0,0.0,306.0,Slow,1,Undiscovered,NaN,NaN,120.0,0.50,1.5,1.0,1.0,0.50,0.50,1.00,0.0,1.5,0.50,0.25,1.00,0.50,1.5,0.5,1.5,0.5,0.5
936,800,Ultra Necrozma,Necrozma,ネクロズマ (Necrozma),7,Legendary,Prism Pokémon,2,Psychic,Dragon,7.5,230.0,1,Neuroforce,NaN,NaN,754,97,167,97,167,97,129,3.0,0.0,339.0,Slow,1,Undiscovered,NaN,NaN,120.0,1.00,0.5,0.5,0.5,0.50,2.00,0.50,1.0,1.0,1.00,0.50,2.00,1.00,2.0,2.0,2.0,1.0,2.0
937,801,Magearna,Magearna,マギアナ (Magearna),7,Mythical,Artificial Pokémon,2,Steel,Fairy,1.0,80.5,1,Soul-Heart,NaN,NaN,600,80,95,115,130,115,65,3.0,0.0,270.0,Slow,1,Undiscovered,NaN,NaN,120.0,0.50,2.0,1.0,1.0,0.50,0.50,1.00,0.0,2.0,0.50,0.50,0.25,0.50,1.0,0.0,0.5,1.0,0.5
944,808,Meltan,Meltan,メルタン (Meltan),7,Mythical,Hex Nut Pokémon,1,Steel,NaN,0.2,8.0,1,Magnet Pull,NaN,NaN,300,46,65,65,55,35,34,3.0,NaN,NaN,Slow,1,Undiscovered,NaN,NaN,120.0,0.50,2.0,1.0,1.0,0.50,0.50,2.00,0.0,2.0,0.50,0.50,0.50,0.50,1.0,0.5,1.0,0.5,0.5
945,809,Melmetal,Melmetal,メルメタル (Melmetal),7,Mythical,Hex Nut Pokémon,1,Steel,NaN,2.5,800.0,1,Iron Fist,NaN,NaN,600,135,143,143,80,65,34,3.0,NaN,NaN,Slow,1,Undiscovered,NaN,NaN,120.0,0.50,2.0,1.0,1.0,0.50,0.50,2.00,0.0,2.0,0.50,0.50,0.50,0.50,1.0,0.5,1.0,0.5,0.5
1000,863,Perrserker,Mauzinger,ニャイキング (Nyaiking),8,Normal,Viking Pokémon,1,Steel,NaN,0.8,28.0,3,Battle Armor,Tough Claws,Steely Spirit,440,70,110,100,50,60,50,90.0,NaN,NaN,Medium Fast,1,Field,NaN,50.0,20.0,0.50,2.0,1.0,1.0,0.50,0.50,2.00,0.0,2.0,0.50,0.50,0.50,0.50,1.0,0.5,1.0,0.5,0.5
1018,878,Cufant,Kupfanti,ゾウドウ (Zoudou),8,Normal,Copperderm Pokémon,1,Steel,NaN,1.2,100.0,2,Sheer Force,NaN,Heavy Metal,330,72,80,49,40,49,40,190.0,NaN,NaN,Medium Fast,2,Field,Mineral,50.0,25.0,0.50,2.0,1.0,1.0,0.50,0.50,2.00,0.0,2.0,0.50,0.50,0.50,0.50,1.0,0.5,1.0,0.5,0.5
1019,879,Copperajah,Patinaraja,ダイオウドウ (Daioudou),8,Normal,Copperderm Pokémon,1,Steel,NaN,3.0,650.0,2,Sheer Force,NaN,Heavy Metal,500,122,130,69,80,69,30,90.0,NaN,NaN,Medium Fast,2,Field,Mineral,50.0,25.0,0.50,2.0,1.0,1.0,0.50,0.50,2.00,0.0,2.0,0.50,0.50,0.50,0.50,1.0,0.5,1.0,0.5,0.5
1024,884,Duraludon,Duraludon,ジュラルドン (Duraludon),8,Normal,Alloy Pokémon,2,Steel,Dragon,1.8,40.0,3,Light Metal,Heavy Metal,Stalwart,535,70,95,115,120,50,85,45.0,NaN,NaN,Medium Fast,2,Dragon,Mineral,50.0,30.0,0.50,1.0,0.5,0.5,0.25,1.00,2.00,0.0,2.0,0.50,0.50,0.50,0.50,1.0,1.0,1.0,0.5,1.0
1028,888,Zacian Crowned Sword,Zacian,ザシアン (Zacian),8,Legendary,Warrior Pokémon,2,Fairy,Steel,2.8,355.0,1,Intrepid Sword,NaN,NaN,720,92,170,115,80,115,148,10.0,NaN,NaN,Slow,1,Undiscovered,NaN,NaN,120.0,0.50,2.0,1.0,1.0,0.50,0.50,1.00,0.0,2.0,0.50,0.50,0.25,0.50,1.0,0.0,0.5,1.0,0.5
1043,898,Calyrex Ice Rider,Coronospa,バドレックス (Budrex),8,Legendary,High King Pokémon,2,Psychic,Ice,2.4,809.1,1,As One,NaN,NaN,680,100,165,150,85,130,50,3.0,NaN,NaN,Slow,1,Undiscovered,NaN,NaN,120.0,1.00,2.0,1.0,1.0,1.00,0.50,1.00,1.0,1.0,1.00,0.50,2.00,2.00,2.0,1.0,2.0,2.0,1.0

In [62]:
# alle Pokemon die nicht Status "normal" haben

normal = df['status'] == 'Normal'

df[~ normal].filter(like='name')

                       name german_name       japanese_name
Index
184                Articuno      Arktos     フリーザー (Freezer)
185       Galarian Articuno      Arktos     フリーザー (Freezer)
186                  Zapdos      Zapdos      サンダー (Thunder)
187         Galarian Zapdos      Zapdos      サンダー (Thunder)
188                 Moltres     Lavados        ファイヤー (Fire)
...                     ...         ...                 ...
1040              Glastrier    Polaross  ブリザポス (Burizaposu)
1041              Spectrier  Phantoross   レイスポス (Reisuposu)
1042                Calyrex   Coronospa     バドレックス (Budrex)
1043      Calyrex Ice Rider   Coronospa     バドレックス (Budrex)
1044   Calyrex Shadow Rider   Coronospa     バドレックス (Budrex)

[127 rows x 3 columns]

## DataFrames sortieren

Oft ist es bei der Beantwortung mancher Fragen, die man sich über seinen Datensatz stellt, hilfreich, den Datensatz nach bestimmten Variablen zu sortieren. So kann man Fragen an den Datensatz stellen wie "was sind eigentlich die kleinsten/größten Pokemon?" oder "welche Pokemon sind am stärksten/schwächsten?" oder auch "welche Pokemon haben die längsten Namen?".

Um einen DataFrame zu sortieren, gibt es die Methode `.sort_values()`.

In [63]:
df['attack'].sort_values()

Index
147      5
526      5
166     10
262     10
294     10
      ...
467    180
464    180
931    181
264    185
194    190
Name: attack, Length: 1045, dtype: int64

Mit dem Parameter "ascending" (= engl. "aufsteigend") den man auf `True` oder `False` setzen kann, kann man die Sortierreihenfolge auf- oder absteigend einstellen.

In [64]:
df['attack'].sort_values(ascending=False)

Index
194    190
264    185
931    181
462    180
464    180
      ...
294     10
262     10
166     10
526      5
147      5
Name: attack, Length: 1045, dtype: int64